#!/bin/bash
set -x #echo on

if [[ -f `pwd`/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "missing file: sharedfuncs"
  exit 1
fi

if [[ "$(id -u)" == "0" ]]; then
	    error_msg "ERROR! You shuld not execute the script as the root user."
fi
prompt=$(sudo -nv 2>&1)
if [ $? -eq 0 ]; then
  print_info "Stay alert!"
elif echo $prompt | grep -q '^sudo:'; then
  print_warning "Stay alert and enter your password if necessary."
else
  error_msg "ERROR! You must execute the script as a sudo user."
fi

check_connection

print_line


sudo pacman -Sy git --needed
arch_dir=$(mktemp -d -t arch-XXXXXXXXXX)
echo "Cloning https://github.com/C0D3D3V/arch to ${arch_dir}"

git clone https://github.com/C0D3D3V/arch $arch_dir


include_file "post_subitems/000_aui_paketverwaltung" 

# Install all packages
comm -13 <(pacman -Qq | sort) <(awk 1 ${arch_dir}/**/* | sed -n -e "s/^[ \t]*+[ \t]*\([^ \t]*\)[ \t]*$/\1/gp" | sort) | yay -Sy --needed --noconfirm -
sudo systemctl daemon-reload





# Activate all services listet in the documentation

awk 1 ${arch_dir}/**/* | sed -n -e "s/^[ \t]*systemctl enable --now[ \t]*\([^ \t]*\)[ \t]*$/\1/gp" | xargs sudo systemctl enable




cecho "CLEAN ORPHAN PACKAGES - https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Removing_unused_packages_.28orphans.29" 

pacman -Rcns --noconfirm $(pacman -Qtdq)

paccache -r -k 0
pacman -Scc --noconfirm

rm -rf $arch_dir

print_line
print_line
cecho "\n\n" 

cecho "Finish :)" 
cecho "Please reboot and enjoy" 
