#!/bin/bash


if [[ -f `pwd`/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "missing file: sharedfuncs"
  exit 1
fi

pls_enter "What do you want to add to the begin of the new log?" 
cecho "$sthInsertion"

check_root
check_boot_system


print_line

print_info "Load German Keymap [https://wiki.archlinux.org/index.php/Keyboard_configuration_in_console]"
#cecho "Be sure to load Keymap with loadkeys de-latin1"
ncecho "loadkeys de-latin1 "
loadkeys de-latin1 >>"$LOG" 2>&1 & 
pid=$!;progress $pid

check_connection

pause_function
 
print_title "This Skript will reset the live install settings"
#lsblk

pause_function

print_line



print_line 

#Mirrorlist
print_title "Backup pacman mirrorlist and filter for German Servers [https://wiki.archlinux.org/index.php/mirrors]"
ncecho "First Dowload full Mirrorlist "


url="https://www.archlinux.org/mirrorlist/?country=DE&use_mirror_status=on"

tmpfile=$(mktemp --suffix=-mirrorlist)
# Get latest mirror list and save to tmpfile
curl -so ${tmpfile} ${url} >>"$LOG" 2>&1 & 
pid=$!;progress $pid

sed -i 's/^#Server/Server/g' ${tmpfile}

if [[ -s ${tmpfile} ]]; then
    { cecho " Backing up the original mirrorlist..."
      mv -i /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.orig; } &&
	{ cecho " Rotating the new list into place..."
	  mv -i ${tmpfile} /etc/pacman.d/mirrorlist; }
else
    print_warning " Unable to update, could not download list."
fi

chmod 644 /etc/pacman.d/mirrorlist

  
#cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
#grep -E -A 1 ".*Germany.*$" /etc/pacman.d/mirrorlist.bak | sed '/--/d' > /etc/pacman.d/mirrorlist.backup

#rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist &
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.tmp

ncecho "Rank Mirrorlist "
rankmirrors /etc/pacman.d/mirrorlist.tmp > /etc/pacman.d/mirrorlist & 
pid=$!;progress $pid

rm /etc/pacman.d/mirrorlist.tmp
chmod 644 /etc/pacman.d/mirrorlist


 
print_line 

print_info "Edit makepkg conf [https://wiki.archlinux.org/index.php/makepkg#tmpfs]"

sed -i "s|#BUILDDIR=/tmp/makepkg|BUILDDIR=/tmp/makepkg|" /etc/makepkg.conf
sed -i "s|PKGEXT='.pkg.tar.xz'|PKGEXT='.pkg.tar'|" /etc/makepkg.conf



print_info "Generate vconsole [https://wiki.archlinux.org/index.php/Keyboard_configuration_in_console]"

echo "KEYMAP=de-latin1" > /etc/vconsole.conf
echo "FONT=lat9w-16" >> /etc/vconsole.conf

cecho "Generate loacls [https://wiki.archlinux.org/index.php/locale]"

echo "LANG=de_DE.UTF-8" > /etc/locale.conf
echo "LC_COLLATE=C" >> /etc/locale.conf
echo "LANGUAGE=de_DE" >> /etc/locale.conf


print_info "Generate Hostname [https://wiki.archlinux.org/index.php/Network_configuration#Set_the_hostname]"


DEVICENAMEENTERED=0
while [ $DEVICENAMEENTERED -eq 0 ];
do
    
    read -p "Please enter a hostname for the system: " devicename
    yn_question "Do you realy want to use ${devicename}?"
    if [ $ynAnswer == "y" ]; then
	DEVICENAMEENTERED=1
    fi
done
echo $devicename > /etc/hostname

print_info "Generate Journalctrl config [https://wiki.archlinux.org/index.php/Systemd#Journal]"


sed -i "s/#Storage=auto/Storage=persistent/" /etc/systemd/journald.conf
sed -i "s/#SystemMaxUse=/SystemMaxUse=400M/" /etc/systemd/journald.conf
sed -i "s/#SystemMaxFileSize=/SystemMaxFileSize=30M/" /etc/systemd/journald.conf
sed -i "s/#RuntimeMaxUse=/RuntimeMaxUse=250M/" /etc/systemd/journald.conf
sed -i "s/#RuntimeMaxFileSize=/RuntimeMaxFileSize=30M/" /etc/systemd/journald.conf



print_info "Generate Timezone [https://wiki.archlinux.org/index.php/Time#Time_zone]"

ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime >>"$LOG" 2>&1 & 
pid=$!;progress $pid

print_info "Setup Hardware Clock [https://wiki.archlinux.org/index.php/Time]"


hwclock --systohc --localtime >>"$LOG" 2>&1 & 
pid=$!;progress $pid


print_line

print_info "Setup Locals [https://wiki.archlinux.org/index.php/Locale]"

sed -i "s/#de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/" /etc/locale.gen
sed -i "s/#de_DE ISO-8859-1/de_DE ISO-8859-1/" /etc/locale.gen
sed -i "s/#de_DE@euro ISO-8859-15/de_DE@euro ISO-8859-15/" /etc/locale.gen
sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/" /etc/locale.gen
sed -i "s/#en_US ISO-8859-1/en_US ISO-8859-1/" /etc/locale.gen

ncecho "Generate locales"
locale-gen >>"$LOG" 2>&1 & 
pid=$!;progress $pid


print_line

print_info "Activate Multilib  [https://wiki.archlinux.org/index.php/multilib]"
#SigLevel = PackageRequired TrustedOnly


sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

#cecho "Please aktivate multilib by uncomment following lines: "
#cecho "#[multilib]"
#cecho "#Include = /etc/pacman.d/mirrorlist"

#read -p "Press enter to get into editor"

#nano /etc/pacman.conf
 
ncecho "Update Repos"
pacman -Sy  >>"$LOG" 2>&1 & 
pid=$!;progress $pid
 

print_line

print_info "Set Root Password  [https://wiki.archlinux.org/index.php/users_and_groups]"
ynAnswer="n"
while [ $ynAnswer == "n" ];
do
    passwd
    yn_question "Did you set the password correct?"
done


print_line
 

print_line

cecho "\n\n"

cecho "Setup finished"  
