#!/bin/bash

if [[ -f `pwd`/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "missing file: sharedfuncs"
  exit 1
fi

check_root

print_line

print_line

ping -c 2 google.com
cecho "Connect to wifi [https://wiki.archlinux.org/index.php/netctl]"
cecho "Be sure to connect to Wifi with: wifi-menu"

cecho "Or Connect to ethernet [https://bbs.archlinux.org/viewtopic.php?id=210679]"
cecho "Be sure to connect to Ethernet with: "
cecho "ip link set enpxxxx up  "
cecho "dhcpcd" 

print_line

cecho "This Skript will install my lovely system"
cecho "Be sure that you want to install all the software"

print_line

cecho "A clean Arch installation is requested" 

print_line

read -p "Press enter to continue"

print_line

