#!/bin/bash

if [[ -f `pwd`/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "missing file: sharedfuncs"
  exit 1
fi

print_title "Das ist ein Test"

pause_function

print_info "Jetzt gehts los!"

username="c0d3d3v"
check_root
#aur_package_install "ddnet"

