#!/bin/bash


print_title "Install DEVELOPMENT APPS"



print_info "Install cmake"  
package_install "cmake"

print_info "Install binwalk"  
package_install "binwalk"



print_info "Install sqlite3"  
package_install "sqlite3"

#languages
#NOTMARCEL ALLE SPRECHEN
print_info "Install nodejs"  
package_install "nodejs npm"


print_info "Install ruby"  
package_install "ruby"
aur_package_install "rbenv ruby-build"


print_info "Install elixir"  
package_install "elixir"


print_info "Install go"  
package_install "go"

print_info "Install Haskel"  
package_install "ghc"

print_info "Install clang"  
package_install "clang"



