#!/bin/bash


print_title "Create a new user"



if [ $skip_user_config -eq 0 ]; then
    
    useradd -m -g users -G wheel -s /bin/bash $username
    add_user_to_group $username $username
    chfn $username
    
    ################# User Action ##################
    #user data
    ynAnswer="n"
    while [ $ynAnswer == "n" ];
    do
        passwd $username
	yn_question "Did you set the password correct?"
    done
    
    ################# User Action ##################
    #password eingabe



    #pause_function

    print_line

    print_info "Load Bash Config"  
    #bash conf resource (bsp: https://github.com/helmuthdu/dotfiles)
    cp /etc/skel/.bashrc /home/$username
    #groupadd $username
    #add_user_to_group $username $username
    chown -R ${username}:${username} /home/$username    #config files gehören dem user

    print_info "Make him sudoer"
    package_install "sudo"

    cecho "Backup /etc/sudoers to /etc/sudoers.aui"

    cp -v /etc/sudoers /etc/sudoers.aui
    sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /etc/sudoers

    cecho "Config sudo"
    echo "" >> /etc/sudoers
    echo 'Defaults !requiretty, !tty_tickets, !umask' >> /etc/sudoers
    echo 'Defaults visiblepw, path_info' >> /etc/sudoers #insults
    #loglinelen=0, logfile =/var/log/sudo.log, log_year, log_host, 
    echo 'Defaults syslog=auth' >> /etc/sudoers
    echo 'Defaults passwd_tries=3, passwd_timeout=1' >> /etc/sudoers
    echo 'Defaults env_reset' >> /etc/sudoers
    echo 'Defaults !env_editor, editor="/usr/bin/vim:/usr/bin/vi:/usr/bin/nano"' >> /etc/sudoers
    echo 'Defaults timestamp_timeout=15' >> /etc/sudoers
    echo 'Defaults passprompt="[sudo] password for %u: "' >> /etc/sudoers
    echo 'Defaults lecture=never' >> /etc/sudores


fi

#pause_function

print_line
