#!/bin/bash


print_title "Install base components"

if ! is_package_installed "yay" ; then


  print_info "Istall yay - https://github.com/Jguer/yay"
  #fix mirrorlist
  chmod 644 /etc/pacman.d/mirrorlist
  package_install "base-devel yajl namcap"
  aui_download_packages "package-query yay"

  print_warning "Be sure the installation of yay succeeded!"
  pause_function

  print_line

fi

print_info "Install Bash tools" 
package_install "bc rsync mlocate bash-completion" #pkgstats arch-wiki-lite
# bc - Für Berechnungen in Bash  --- guter Taschenrechner
# rsync - Besseres Copy https://wiki.archlinux.org/index.php/Rsync
# mlocate - speed up find https://wiki.archlinux.org/index.php/Mlocate
# bash-completion - autocompletion für bash https://wiki.archlinux.de/title/Bash-Completion


print_line

print_info "Install compress tools" 
package_install "zip unzip unrar p7zip lzop cpio"
# Archivierungs Tools - https://wiki.archlinux.org/index.php/Archiving_and_compression
# für .zip .rar .7z .tzo tar general


print_line


print_info "Install AVAHI - https://wiki.archlinux.org/index.php/Avahi" 
package_install "avahi nss-mdns"
system_ctl enable avahi-daemon

# Zum finden von Geräten im Netzwerk ... Service Discovery - Drucker finden
# nss-mdns -  locale hostnamen auflösen

print_line

if [ $isServer == "n" ]; then
    print_info "Install ALSA - https://wiki.archlinux.org/index.php/Alsa" 
    package_install "alsa-utils alsa-plugins"

    # treiber für sound karten
    # alse-plugin - für upmixing/downmixing etc. ... "high quality resampling"

    print_info "Install PULSEAUDIO - https://wiki.archlinux.org/index.php/Pulseaudio" 
    package_install "pulseaudio pulseaudio-alsa"
    # Audio Server - verwinfacht allerlei Konfigurationen die mit Audio zu tun haben
    # pulseaudio-alsa, for PulseAudio to manage ALSA 
    print_line
fi


print_info "Install NTP - https://wiki.archlinux.de/title/NTP" 
package_install "ntp"
system_ctl enable ntpd 
# synchronize software clock mit der internet zeit

print_line



print_info "Install acpid - https://wiki.archlinux.org/index.php/acpid" 
package_install "acpid" 
system_ctl enable acpid 
# verarbeitet acpi events - spezial tasten, notebook schließen, kopfhörer eingesteckt...

print_line



print_info "Install dbus - https://wiki.archlinux.org/index.php/D-Bus" 
package_install "dbus" 
# Ermöglicht die Kommunikation zwischen Anwendungen (wird von systemd sowiso installiert)

print_line


print_info "Install ssh - https://wiki.archlinux.de/title/SSH" 
package_install "openssh sshfs" #keychain 
# openssh - verbindung mit anderen computer herstellen
# sshfs - dateisystem von anderem computer mounten


print_line

print_info "Install cronie - https://wiki.archlinux.org/index.php/Cron" 
package_install "cronie" 
system_ctl enable cronie
# time based scheduler

print_line

print_info "Install NTFS/FAT/exFAT/F2FS - https://wiki.archlinux.org/index.php/File_Systems" 
package_install "ntfs-3g dosfstools exfat-utils f2fs-tools fuse autofs mtpfs"
# Dateisysteme
# Windows -  ntfs-3g
# Vfat - dosfstools
# exfat - exfat-utils
# F2FS - f2fs-tools
# fuse - file systems in user space
# autofs - automatisches mounten von Dateisystemen
# mtpfs - media transfer protocol - um Dateien auf Handys zu kopieren



#pause_function

print_line

print_info "Install ZSH - https://wiki.archlinux.org/index.php/Zsh" 
package_install "zsh wget curl git zsh-completions"
aur_package_install "zsh-autosuggestions antigen-git"

# zsh - eine der besten Shells
# wget - HTTP Dateien downloaden https://wiki.archlinux.org/index.php/Wget
# curl selbe
# zsh-completions - mehr autocompletion
# zsh-autosuggestion - noch mehr autocompletion (wie fish)
# antigen-git - plugin manager for zsh

package_install "thefuck zsh-theme-powerlevel9k"
# thefuck - korrigiert eingabefehler in der shell
# zsh-theme-powerlevel9k - schönes theme für zsh

#set zsh as default shell
chsh -s /bin/zsh
sed -i 's|^SHELL=/bin/bash|SHELL=/bin/zsh|g' /etc/default/useradd


print_line
print_warning "This is the last pause!"

read -p "Please check .zshrc - Press enter to continue"

print_line

run_as_user "cp /home/${username}/.zshrc /home/${username}/.zshrc.bak"

run_as_user "nano /home/${username}/.zshrc"

run_as_user "chsh -s /bin/zsh"


#pause_function


