#!/bin/bash

print_title "Installing GPU drivers"

GPU_INFO=$(lspci -nn | grep -Ei 'vga|3d|display')

if echo "$GPU_INFO" | grep -qi 'nvidia'; then
	echo "NVIDIA GPU detected"
	echo "Warning if you have an older model than Turing, you have to use an older driver [https://wiki.archlinux.org/title/NVIDIA]"

	yay -Sy --needed --noconfirm nvidia-open-dkms nvidia-utils lib32-nvidia-utils nvidia-settings linux-headers

elif echo "$GPU_INFO" | grep -Eqi 'amd|ati'; then
	echo "AMD GPU / iGPU detected"

	yay -Sy --needed --noconfirm mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon xf86-video-amdgpu

elif echo "$GPU_INFO" | grep -qi 'intel'; then
	echo "Intel GPU / iGPU detected"

	yay -Sy --needed --noconfirm mesa lib32-mesa vulkan-intel lib32-vulkan-intel intel-media-driver linux-firmware-intel
else
	echo "No NVIDIA, Intel, or AMD GPU detected"
fi
