#!/bin/bash


print_title "Install accessories APPS"


#NOTMARCEL
print_info "Install conky-lua - Sensore Gadgets"  
aur_package_install "conky-lua"
package_install "lm_sensors"
sensors-detect --auto





#NOTMARCEL
print_info "Install conky-lua - Pacman GUI"  
aur_package_install "pamac-aur"

#enpass-bin passwort manager





#print_info "Install terminator - Terminal multiplexer"   
#package_install "terminator"

print_info "Install tmux - Terminal multiplexer"   
package_install "tmux"

#unified-remote-server Remote tools


