#!/bin/bash


print_title "Install accessories APPS"

if [ $isServer == "n" ]; then
    #NOTMARCEL
    print_info "Install conky-lua - Sensore Gadgets"  
    aur_package_install "conky-lua"
    package_install "lm_sensors"
    sensors-detect --auto






    #enpass-bin passwort manager


    print_info "Install Anki, Nitrokey, evince PDF reader" 
    package_install "anki nitrokey-app evince"
    
    
fi


#print_info "Install terminator - Terminal multiplexer"   
#package_install "terminator"

print_info "Install tmux - Terminal multiplexer"   
package_install "tmux"

#unified-remote-server Remote tools


