#!/bin/bash


print_title "Install DEVELOPMENT APPS"


#Editors
print_info "Install emacs - Best Editor"  
package_install "emacs terminus-font" 

print_info "Install vim - Some Editor"  
package_install "vim" 







print_info "Install sublime3 - Nice Editor"  
aur_package_install "sublime-text-dev" 
#aur_package_install "sublime-text" 






cecho "Install codeblocks"  
package_install "codeblocks"






print_info "Install Android Studio"  
run_as_user "gpg --recv-keys 702353E0F7E48EDB"
aur_package_install "android-sdk android-sdk-platform-tools android-sdk-build-tools android-platform  android-ndk"

add_user_to_group $username sdkusers
chown -R :sdkusers /opt/android-sdk/
chmod -R g+w /opt/android-sdk/
add_line "export ANDROID_HOME=/opt/android-sdk" "/home/${username}/.bashrc"

touch /opt/android-studio/bin/studio64.vmoptions
add_line "-Djava.io.tmpdir=/var/tmp/" "/opt/android-studio/bin/studio64.vmoptions"

aur_package_install "android-studio"

add_user_to_group $username plugdev







print_info "Install monodevelop - dot net shit"  
package_install "monodevelop monodevelop-debugger-gdb"
#fix https://bugs.archlinux.org/task/52939
ln -s /usr/lib/libgit2.so /usr/lib/libgit2-e8b8948.so





print_info "Install qtcreator"  
package_install "qtcreator qt5-doc" #android-qt5-arm64-v8a #dont install this .... shitty compile time 8h





print_info "Install MySQL Workbench"  
package_install "mysql-workbench"

print_info "Install postgress Admin"
package_install "pgadmin4"

print_info "Install sqlite3"  
package_install "sqlite3"

print_info "Install H2"  
aur_package_install "h2"




print_info "Install OpenJDK"  
#maybe switch to oracle shit
package_install "jdk8-openjdk icedtea-web"  
archlinux-java set java-8-openjdk/jre

print_info "Install eclipse"  
package_install "eclipse-jee tomcat8"
add_user_to_group $username tomcat8


print_info "Install intellij - just more shit"  
package_install "intellij-idea-community-edition"








#languages 
print_info "Install nodejs"  
package_install "nodejs npm"


print_info "Install ruby"  
package_install "ruby"
aur_package_install "rbenv ruby-build"


print_info "Install elixir"  
package_install "elixir"


print_info "Install go"  
package_install "go"

print_info "Install Haskel"  
package_install "ghc"

print_info "Install clang"  
package_install "linter-clang clang"


print_info "Install Ardoino"  
package_install "arduino arduino-avr-core"








#tools
cecho "Install gource"  
package_install "gource"





#mockups
#cecho "Install balsamiqmockups"  
#aur_package_install "balsamiqmockups" #dont install this shit... Hat wine als Dep.




