#!/bin/bash


print_title "Install DEVELOPMENT APPS"

if [ $isServer == "n" ]; then
    #Editors
    print_info "Install emacs - Best Editor"  
    package_install "emacs terminus-font" 
    # emacs is nicer editor

    print_info "Install gvim - Vi with gui"  
    package_install "gvim"
    # vim is auch mindestens genauso krass
    

    print_info "Install diffuse"  
    package_install "diffuse"
    # diffuse - mergen von dateien mit einer gui


    print_info "Install bless Hex-Editor"  
    package_install "bless"
    # guter hex editor

    
    print_info "Install radare2"
    package_install "radare2"
    # hex editor cli
    
    print_info "Install cmake"  
    package_install "cmake"
    # willst du etwas c compilieren?
    
    print_info "Install binwalk"  
    package_install "binwalk"
    # willst bar images ausenander pflücken?


    # Android Studio
    aur_package_install "android-studio"
    package_install "android-tools android-udev "
    add_user_to_group $username plugdev


    
    cecho "Install sqlitebrowser"  
    package_install "sqlitebrowser"
    # browse sqllite database



    print_info "Install OpenJDK"  
    package_install "jdk8-openjdk icedtea-web"  
    archlinux-java set java-8-openjdk/jre
    # run java

    
    print_info "Install intellij"  
    package_install "intellij-idea-community-edition"
    # for noobs some gui
    

    print_info "Install jadx - decompiler for java"  
    package_install "jadx"
    # decompile java


    # Arduino Studio
    print_info "Install Ardoino"  
    package_install "arduino arduino-avr-core"


    # git version tree
    print_info "Install gource"  
    package_install "gource"


    
    print_info "Install emacs plugins"
    aur_package_install "emacs-elpy"
    package_install "the_silver_searcher ripgrep"


    print_info "Install nasm"
    package_install "nasm"
    # netwide assembler - willst bissel assembler programmieren?

    # Wichtige Sprachen
    print_info "Install Python"
    package_install "python python2 python-pip"

    
    print_info "Install Go"
    package_install "go"
fi

# upload output to pastebin
print_info "Install pastebinit"  
package_install "pastebinit"


if [ $isServer == "y" ]; then
  print_info "Install vim - Some Editor"  
  package_install "vim" 
  
fi
