#!/bin/bash


print_title "Install office APPS"

if [ $isServer == "n" ]; then
    # bücher lesen
    print_info "Install calibre"  
    package_install "calibre"

    # latex mit texstudio als basic editr ... emacs kann auch gut mit latex umgehen
    print_info "Install latex + texstudio"  
    package_install "texlive-most  texlive-bin texstudio biber" #texlive-lang



    #office
    print_info "Install Libreoffice - https://wiki.archlinux.org/index.php/LibreOffice"
    package_install "libreoffice-fresh-de"
    package_install "hunspell hunspell-de"
    package_install "aspell aspell-de aspell-en"



    # Scan Tools
    print_info "Install gscan2pdf - Simple scan tool" 
    aur_package_install "gscan2pdf"

    print_info "Install simple-scan" 
    package_install "simple-scan"

    # einfache Druckerverwaltung
    package_install "print-manager"
    
    
    #pdf viewer
    package_install "okular evince"
    # evince - noch ein pdf viewer ... manchmal ist der besser als okular
    
    # PDF Editor
    print_info "Install masterpdfeditor"   
    aur_package_install "masterpdfeditor"


    # Diverse PDF tools
    print_info "Install diffpdf pdf-decrypt pdf2png pdfgrep"  
    package_install "pdfgrep"
    aur_package_install "diffpdf pdf-decrypt pdf2png"
    # pdfgrep - suchen in pdfs
    # diffpdf - pdfs vergleichen
    # pdf-decrypt - verschlüsselte pdfs ... entschlüsseln
    # pdf2png - pdfs in pngs umwandelnd
    
    # UML Diagramme etc.
    print_info "Install dia - uml tool"   
    package_install "dia"



    # Notizen mit Stylus
    print_info "Install xournal" 
    package_install "xournal"


    
    # Anki - Karteikarten Software
    print_info "Install Anki" 
    package_install "anki"
    
    

fi
