#!/bin/bash


print_title "Install system APPS"



if [ $isServer == "n" ]; then


    # to monitor networktrafic
    print_info "Install wireshark  - https://wiki.archlinux.org/index.php/wireshark"
    package_install "wireshark-qt"
    add_user_to_group $username wireshark

    print_info "Install ettercap"
    package_install "ettercap-gtk"



    # gdb - ein beliebter Debugger
    # peda - exploit tools for gdb
    print_info "Install gdb with peda"
    package_install "gdb peda"
    

    # tools für wifi-exploits
    if [ $wifiPenTools == "n" ]; then  
	print_info "Install Aircrack-ng"
	package_install "aircrack-ng cowpatty"
	aur_package_install "reaver-wps-fork-t6x pyrit-git wifite-git" #pixiewps-git  #reaver-wps-fork-t6x-git
    fi


    # remove ssl :D mitm
    print_info "Install sslstrip"
    package_install "sslstrip"


    # Vitual Machines
    print_info "Install virtualbox "
    package_install "virtualbox linux-headers virtualbox-guest-iso" #virtualbox-host-modules-arch
    aur_package_install "virtualbox-ext-oracle"
    add_user_to_group $username vboxusers
    modprobe vboxdrv vboxnetflt

    
    # Wacom support
    if [[ $wacomSupport == y ]]; then
	print_info "Install Wacom suport - https://wiki.archlinux.org/index.php/wacom_tablet"
	package_install "xf86-input-wacom libwacom" 
	aur_package_install "kcm-wacomtablet" 
    fi

    # Tablet Support
    if [[ $tebletSupport == y ]]; then
	print_info "Install Tablet suport - https://wiki.archlinux.org/index.php/Tablet_PC"
	aur_package_install "iio-sensor-proxy" 
    fi

    
    print_info "Install xbindkeys"
    package_install "xbindkeys"
    # bind things on keys :D 

    
    print_info "Install HDD info"
    package_install "smartmontools gsmartcontrol"
    # check hdd health

    print_info "Install powertop"
    package_install "powertop"
    # prüfen wo die ganze Energie hinfließt
    

    print_info "Install smartcard things"
    package_install "ccid pcsc-tools opensc"


    # noch ein diff tool für Dateien - cli - weils so schön ist
    print_info "Install icdiff - netter diff"
    package_install "icdiff"
fi



cecho "Install truecrypt"
package_install "truecrypt"
# encrypt devices


print_info "Install pv - A terminal-based tool for monitoring the progress of data through a pipeline"
package_install "pv"
# monitor progess


print_info "Install lsof"
package_install "lsof"
# monitor geöffnete dateien



print_info "Install strace ltrace"
package_install "strace ltrace"
# trace system calls

 
print_info "Install traceroute"
package_install "traceroute"
# trace the route of packages


print_info "Install whois"
package_install "whois"
# who is behind a domain


print_info "Install gdisk"
package_install "gptfdisk"
# bissel an partitionen arbeiten ?



print_info "Install htop - Systemmonitor"
package_install "htop"
# taskmanager - cli


print_info "Install xclip"
package_install "xclip"
# copy terminal to clipboard


#System Information
print_info "Install hwinfo and hardinfo"
package_install "hwinfo hardinfo"
# hwinfo - cli
# hardinfo - gui


print_info "Install tree"
package_install "tree"

print_info "Install nmap"
package_install "nmap"


print_info "Install gnu-netcat"
package_install "gnu-netcat"




print_info "Install pkgfile"
package_install "pkgfile"


print_info "Install bind-tools"
package_install "bind-tools"



print_info "Install mtr - ping tool"
package_install "mtr"


print_info "Install oping - ping tool"
package_install "liboping"

print_info "Install httpie - liefert http comand"
package_install "httpie"

print_info "Install aria2 - super downloader "
package_install "aria2"

print_info "Install jq - json file tool"
package_install "jq"

print_info "Install ripgrep - rg schnelles grep"
package_install "ripgrep"

print_info "Install fd - schnelles find - smartCase"
package_install "fd"

print_info "Install exa - schönes ls"
package_install "exa"

print_info "Install fzf - fuzzy scanner integriert in vim tmux zsh -- ctr+t alt+c -- kill"
package_install "fzf"


print_info "Install ranger - cli explorer"
package_install "ranger atool ffmpegthumbnailer highlight lynx mediainfo odt2txt transmission-cli w3m "


print_info "Install mosh -- better ssh"
package_install "mosh"

print_info "Install colordiff - buntes diff"
package_install "colordiff"

print_info "Install progress -- fortshritt"
package_install "progress"


print_info "Install ncdu -- dateigroesse"
package_install "ncdu"

print_info "Install git-lfs -- push große dateien auf github"
package_install "git-lfs"


print_info "Install moreutils -- nice tools like ts"
package_install "moreutils"

print_info "Install Bluetooth"
package_install "bluez bluez-utils pulseaudio-bluetooth "

system_ctl enable bluetooth
add_user_to_group $username lp

print_info "Install paccache --- clean pacman cache"
package_install "pacman-contrib"
system_ctl enable paccache.timer






