#!/bin/bash


print_title "Install graphics APPS"

if [ $isServer == "n" ]; then
    # Bilder bearbeiten
    print_info "Install gimp" 
    package_install "gimp"

    # Vektor Grafiken bearbeitne
    print_info "Install inkscape - Vektrografiken" 
    package_install "inkscape"

    # webcam bilder
    print_info "Install cheese" 
    package_install "cheese"

    # via cli
    package-install "maim"
    
    #picture view - feh einer der schnellsten Image Viewer
    package_install "feh"


fi
