#!/bin/bash


print_title "Install DOWNLOAD tools"

if [ $isServer == "n" ]; then
 
    # JDownloader is a nice download helper
    print_info "Install JDownlaoder2" 
    aur_package_install "jdownloader2"

    # torrent downloader
    print_info "Install transmission-qt - BitTorrent client" 
    package_install "transmission-qt"

    # sync data between multiple devices
    print_info "Install syncthing"
    package_install "syncthing"



fi
