#!/bin/bash


print_title "Install DOWNLOAD tools"


#cecho "Install deluge - bittorrent client" 
#package_install "deluge"

#cecho "Install rslsync - bittorrent sync" 
#aur_package_install "rslsync"



print_info "Install JDownlaoder2" 
aur_package_install "jdownloader2"

#NOTMARCEL
print_info "owncloud client"
package_install "owncloud-client"

print_info "Install transmission-qt - BitTorrent client" 
package_install "transmission-qt"
