#!/bin/bash


print_title "Install email tools"

if [ $isServer == "n" ]; then
    # thunderbird is a overloaded email client
    print_info "Install thunderbird" 
    package_install "thunderbird"
    package_install "thunderbird-i18n-de"

fi
