#!/bin/bash


print_title "Install Instant Messanger"

if [ $isServer == "n" ]; then
    
    print_info "Install weechat"
    # irc client
    package_insall "weechat"

    # group chat
    print_info "Install teamspeak3" 
    package_install "teamspeak3"

    # xmpp client
    print_info "Install gajim" 
    package_install "gajim"
    aur_package_install "gajim-plugin-omemo"


fi
