#!/bin/bash


print_title "Install Audio Tools"



if [ $isServer == "n" ]; then
    
    # spotify
    print_info "Install spotify" 
    aur_package_install "spotify"


    print_line
    cecho "Install Audio editor" 
    # Gutes Audio Schnittprogram
    print_info "Install audacity" 
    package_install "audacity"



    print_line

    # Plugins für pulsaudio
    cecho "Install Audio firmeware"
    package_install "alsa-firmware pulseaudio-equalizer pulseaudio-jack pulseaudio-lirc pulseaudio-zeroconf"




fi
