#!/bin/bash


print_title "Install VIDEO APPS"

if [ $isServer == "n" ]; then

    # overloaded movie player
    print_info "Install vlc"
    package_install "vlc"

    # light movie player
    print_info "Install mpv" 
    package_install "mpv"

    print_info "Install CLI Control" 
    package_install "playerctl"
fi
