#!/bin/bash


print_title "Install Trololol"

if [ $isServer == "n" ]; then

    # Ich mag Züge
    print_info "Install sl" 
    package_install "sl"

    # Die Matrix
    print_info "Install cmatrix" 
    package_install "cmatrix"


fi
